### ISSUE TITLE
Question: Authorization Code Grant Flow

### ISSUE THREAD

**Issue by raghavgarg1257** [slavab89/oauth2-server-example-mongodb#4]
Hey, 

Thanks a lot, for the example repo, Its been really helpful. But I am getting stuck while making the **flow**. I have a question regarding this, can you please answer it?

While using `authorization_code` grant flow, it is asking for `access token` in the request, which will be retrieved using `client_credential` grant flow. I want to know: 
> is there some configuration is given to us using which we can just use `authorization_code` flow without `access_token`(essentially, without authenticating the client)?".

Thanks.

**Comment by slavab89** [comment]
Based on [section of code here](https://github.com/oauthjs/node-oauth2-server/blob/master/lib/handlers/authorize-handler.js#L239) you can override the `authenticateHandler ` with your own logic and return the user relevant to the authorization flow.

The whole point of getting an `authorization_code` is that you should already have an authenticated user using some method. Once you have a `authorization_code` (which should contain all the needed data about the user) you just swap it to an `access token`.

The default behavior of asking an access token is just an example of how you can pass a "verified" user information to that flow. You can also do some login beforehand, save it in a session and then during `authorization_code` take the info from the session. Another option is do login, create a token (with the password flow) and then send that token with the `authorization_code`.

This is for OAuth2 - since OAuth2 handles only authorization.
If you would like to have authorization + authentication in 1 flow you might consider looking at OpenID Connect

**Comment by raghavgarg1257** [comment]
Okay, now it's working.
Thanks a lot for your help.

**Comment by raghavgarg1257** [comment]
If you will, please answer me one more question. In `refresh_token` request we have two ways to send client credentials:
- `Authorization` header with encoded(`base64`) client credentials.
- Client credentials in the body.

It's working with both techniques. Please share why the encoded header is preferred(mentioned in the readme) over body parameters.?

**Comment by slavab89** [comment]
You can read a little about the reason here: https://tools.ietf.org/html/rfc6749.html#section-2.3.1
The reasoning behind it:
https://security.stackexchange.com/questions/46968/why-does-oauth2-demand-client-credentials-in-an-authorization-header
https://stackoverflow.com/questions/44075436/why-does-oauth2-0-says-client-password-in-request-body-not-recommended

**Comment by raghavgarg1257** [comment]
Thanks for, all your help. 👍
